version: '3.8'

services:
  app:
    build: 
      context: ./
      args:
        GID: ${GID}
        USER: ${USER}
        
      dockerfile: Dockerfile.prod
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    image: ${IMAGE_NAME}

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static_vol:
  media_vol: