version: '3.8'

services:
  app:
    build: 
      context: ./
      args:
        GID: ${GID}
        USER: ${USER}
        
      dockerfile: Dockerfile.prod
    volumes:
      # - static_vol:/app/static
      # - media_vol:/app/media
      # - .:.
      - ~/.aws/:/root/.aws:ro
      - /var/www/html:/var/www/html
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    image: ${IMAGE_NAME}
    networks:
      - main

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    # networks:
    #   - main
    volumes:
      # - .:.
      - ./data/nginx:/etc/nginx/conf.d
      # - /var/secure-api/data/certbot/conf:/etc/letsencrypt
      # - /var/secure-api/data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  cerbot:
    image: certbot/certbot
  # certbot-auto:
  #   build:
  #     context: ./certbot-initial
    volumes:
      # - /var/secure-api/data/certbot/conf:/etc/letsencrypt
      # - /var/secure-api/data/certbot/www:/var/www/certbot 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    # env_file:
    #   - ./.env-cert.prod
    

# volumes:
  # static_vol:
  # media_vol:
  # ~/.aws/:
  # .:
networks:
    main:
      driver: bridge   