name: covid_prediction
dependencies:
 - rdkit::rdkit>=2018.03
 - pip:
   - hypopt
   - pprint
   - argparse
   - tqdm
   - xgboost==0.90
   - matplotlib==3.1.1
   - seaborn==0.9.0
   - cairosvg==2.4.2